### PR TITLE
Steps to deployment

### PR DESCRIPTION
**Pull request by J-Bannach**
- Installed express.js
- Added start script
-  Added express server and defined Port

### CODE REVIEW

**Review by jujuzitroni — APPROVED** [review]
lgtm!

i liked your description, very helpful!

**Review by SGierszewski — APPROVED** [review]
LGTM 🚀

**Review by Maurizio-F — APPROVED** [review]
lgtm 🚀

**Review by dhnazarenko — APPROVED** [review]
lgtm 🚀

**Review by Dev-dfm — APPROVED** [review]
lgtm 🚀

**Review by daebert — APPROVED** [review]
lgtm!

**Pull request merged**
